jnn-2005-c-hassaku/naganocake

- Gemfile
- Gemfile.lock
- config/routes.rb
> Hiroki.bootstrap1

- Gemfile
- Gemfile.lock
- app/views/kaminari/_first_page.html.erb
- app/views/kaminari/_gap.html.erb
- app/views/kaminari/_last_page.html.erb
- app/views/kaminari/_next_page.html.erb
- app/views/kaminari/_page.html.erb
- app/views/kaminari/_paginator.html.erb
- app/views/kaminari/_prev_page.html.erb
- config/initializers/kaminari_config.rb
> [Add] gem'kaminari'

- config/routes.rb
> [Add] root'home#top'

- app/controllers/application_controller.rb
- app/views/customers/registrations/new.html.erb
- db/migrate/20200616093842_add_columns_to_customers.rb
- db/schema.rb
def change
add_column :customers, :first_name, :string
add_column :customers, :last_name, :string
add_column :customers, :first_name_kana, :string
add_column :customers, :last_name_kana, :string
add_column :customers, :postcode, :string
add_column :customers, :address, :string
add_column :customers, :account_status, :boolean
add_column :customers, :phone_number, :string
end
> hiroki.add.signup

- app/views/layouts/_header.html.erb
> add.customer.headline

- app/views/layouts/_header.html.erb
> add.headline

- app/assets/stylesheets/application.scss
- app/views/home/top.html.erb
> [Update] top_page

- app/assets/stylesheets/application.scss
- app/views/layouts/_header.html.erb
- app/views/layouts/application.html.erb
> [Update] header

- app/views/customers/registrations/new.html.erb
- app/views/customers/sessions/new.html.erb
> [Update]form

- app/controllers/admins/confirmations_controller.rb
- app/controllers/admins/omniauth_callbacks_controller.rb
- app/controllers/admins/passwords_controller.rb
- app/controllers/admins/registrations_controller.rb
- app/controllers/admins/sessions_controller.rb
- app/controllers/admins/unlocks_controller.rb
- app/models/admin.rb
- app/views/admins/confirmations/new.html.erb
- app/views/admins/mailer/confirmation_instructions.html.erb
- app/views/admins/mailer/email_changed.html.erb
- app/views/admins/mailer/password_change.html.erb
- app/views/admins/mailer/reset_password_instructions.html.erb
- app/views/admins/mailer/unlock_instructions.html.erb
- app/views/admins/passwords/edit.html.erb
- app/views/admins/passwords/new.html.erb
- app/views/admins/registrations/edit.html.erb
- app/views/admins/registrations/new.html.erb
- app/views/admins/sessions/new.html.erb
- app/views/admins/shared/_error_messages.html.erb
- app/views/admins/shared/_links.html.erb
- app/views/admins/unlocks/new.html.erb
- app/views/layouts/_header.html.erb
- config/routes.rb
- db/migrate/20200617070204_devise_create_admins.rb
- db/schema.rb
- db/seeds.rb
- test/fixtures/admins.yml
- test/models/admin_test.rb
管理者でログインするとヘッダーが変わるところまで作りました。
adminのログインページは/admins/sign_inで行けます。
> [Update] admin_login

- app/controllers/admins/home_controller.rb
- app/controllers/application_controller.rb
- app/views/admins/home/top.html.erb
- config/routes.rb
管理者がログイン後、管理者トップページへ遷移できるようにしました。
> [Update] admin_top

- app/assets/javascripts/shipping_addresses.coffee
- app/assets/stylesheets/shipping_addresses.scss
- app/controllers/shipping_addresses_controller.rb
- app/helpers/shipping_addresses_helper.rb
- app/models/category.rb
- app/models/customer.rb
- app/models/product.rb
- app/models/shipping_address.rb
- app/views/layouts/application.html.erb
- db/migrate/20200617085303_create_shipping_addresses.rb
- db/migrate/20200617085555_add_columns_to_shipping_addresses.rb
- db/migrate/20200617091438_create_categories.rb
- db/migrate/20200617091534_add_columns_to_categories.rb
- db/migrate/20200617092851_create_products.rb
- db/migrate/20200617093518_change_data_sale_status_to_products.rb
- db/schema.rb
- test/controllers/shipping_addresses_controller_test.rb
- test/fixtures/categories.yml
- test/fixtures/products.yml
- test/fixtures/shipping_addresses.yml
- test/models/category_test.rb
- test/models/product_test.rb
- test/models/shipping_address_test.rb
> add.model.addres,product,category

- app/assets/javascripts/admins/categories.coffee
- app/assets/stylesheets/admins/categories.scss
- app/assets/stylesheets/application.scss
- app/controllers/admins/categories_controller.rb
- app/helpers/admins/categories_helper.rb
- app/views/admins/categories/edit.html.erb
- app/views/admins/categories/index.html.erb
- test/controllers/admins/categories_controller_test.rb
> [Add] category

- app/controllers/shipping_addresses_controller.rb
- app/views/shipping_addresses/edit.html.erb
- app/views/shipping_addresses/index.html.erb
> shipping_address

- app/assets/stylesheets/application.scss
- app/controllers/home_controller.rb
- app/controllers/shipping_addresses_controller.rb
- app/views/admins/categories/edit.html.erb
- app/views/admins/categories/index.html.erb
- app/views/admins/registrations/new.html.erb
- app/views/customers/registrations/new.html.erb
- app/views/home/top.html.erb
- app/views/layouts/_header.html.erb
- app/views/shipping_addresses/edit.html.erb
- app/views/shipping_addresses/index.html.erb
配送先とジャンル機能部分のビューを整えました。
トップページでジャンルの一覧も表示できるようにしています。
> [Update] category and shipping_address views

- app/assets/stylesheets/application.scss
- app/views/layouts/_header.html.erb
- app/views/layouts/application.html.erb
検索フォームの見た目だけ管理者側のヘッダー下に表示できるようにしました。
> [Add] search_form

- app/assets/stylesheets/application.scss
- app/controllers/shipping_addresses_controller.rb
- app/views/admins/categories/index.html.erb
- app/views/shipping_addresses/index.html.erb
配送先住所一覧をその顧客のもののみを表示できるようにしました。
> [Uppdate] shipping_address

- app/controllers/admins/products_controller.rb
- app/views/admins/products/show.html.erb
> add.product.destroy

- app/assets/stylesheets/application.scss
- app/views/layouts/_header.html.erb
> [Add] hambargar menu

- app/controllers/admins/products_controller.rb
- app/models/product.rb
- app/views/admins/products/edit.html.erb
- app/views/admins/products/index.html.erb
- app/views/admins/products/new.html.erb
- app/views/admins/products/show.html.erb
> price.tax,add

- app/assets/javascripts/products.coffee
- app/assets/stylesheets/products.scss
- app/controllers/products_controller.rb
- app/helpers/products_helper.rb
- app/views/layouts/_header.html.erb
- app/views/products/index.html.erb
- app/views/products/show.html.erb
- test/controllers/products_controller_test.rb
productのindexとshow作成しました。
ヘッダーのリンクも変えてます。
レイアウトは適当です
> product index show

- app/assets/stylesheets/application.scss
> [Update] CSS

- app/assets/stylesheets/application.scss
- app/controllers/admins/products_controller.rb
- app/controllers/home_controller.rb
- app/controllers/products_controller.rb
- app/views/admins/products/edit.html.erb
- app/views/admins/products/index.html.erb
- app/views/admins/products/new.html.erb
- app/views/admins/products/show.html.erb
- app/views/home/_sidebar.html.erb
- app/views/home/top.html.erb
- app/views/products/index.html.erb
- app/views/products/show.html.erb
> [Update] product views

- app/controllers/admins/categories_controller.rb
- app/views/admins/categories/show.html.erb
- app/views/home/_sidebar.html.erb
ジャンル検索機能を作成しました。サイドバーから商品に紐づいたカテゴリーのみの一覧を表示できます。
> [Add] category search

- app/views/layouts/_header.html.erb
> [Update] header link

- app/assets/javascripts/cart_items.coffee
- app/assets/stylesheets/cart_items.scss
- app/controllers/application_controller.rb
- app/controllers/cart_items_controller.rb
- app/controllers/products_controller.rb
- app/helpers/cart_items_helper.rb
- app/models/cart_item.rb
- app/models/customer.rb
- app/models/product.rb
- app/views/cart_items/index.html.erb
- app/views/cart_items/show.html.erb
- app/views/products/show.html.erb
- config/routes.rb
- db/migrate/20200619071101_create_cart_items.rb
- db/migrate/20200619071443_change_quantity_of_cart_items.rb
- db/schema.rb
- test/controllers/cart_items_controller_test.rb
- test/fixtures/cart_items.yml
- test/models/cart_item_test.rb
商品詳細から、createした人の名前、選んだケーキ、値段だけ表示
現状cartitem.allになっているからそこから修正してみてちょ
> add.cartitem.create

- app/controllers/cart_items_controller.rb
- app/models/customer.rb
モデルに書き間違いでログイン系にエラー出てたから修正しました。
再度確認マージお願いします。
> fix.model.cartitem

- app/controllers/cart_items_controller.rb
- app/models/cart_item.rb
- app/views/cart_items/index.html.erb
- config/routes.rb
> add.cartitems.destroy

- app/controllers/cart_items_controller.rb
- app/models/cart_item.rb
- app/views/cart_items/index.html.erb
- app/views/layouts/_header.html.erb
- app/views/products/show.html.erb
・cart_items【コントローラ、indexのビュー】
・【ヘッダーのリンク】
・products【showのビュー】
・数量変更機能
を編集しました。
> Change quantity

- app/views/home/_sidebar.html.erb
カテゴリーにactive_status無効時に表示しない機能を追記しました！
> [Update] category

- app/assets/stylesheets/application.scss
- app/views/products/index.html.erb
- app/views/products/show.html.erb
> [Update] product css

- app/assets/stylesheets/application.scss
- app/views/cart_items/index.html.erb
> [Update] views

- app/models/order.rb
- app/models/order_item.rb
- app/models/product.rb
- db/migrate/20200623030739_create_order_items.rb
- db/schema.rb
- test/fixtures/order_items.yml
- test/models/order_item_test.rb
OrderItemモデルの作成とアソシエーションの設定を行いました。
> [Add] OrderItem model

- app/assets/javascripts/admins/orders.coffee
- app/assets/stylesheets/admins/orders.scss
- app/controllers/admins/orders_controller.rb
- app/helpers/admins/orders_helper.rb
- app/models/customer.rb
- app/views/admins/orders/index.html.erb
- app/views/admins/orders/show.html.erb
- config/routes.rb
- test/controllers/admins/orders_controller_test.rb
> add.admins.order

- app/controllers/admins/orders_controller.rb
- app/models/order.rb
- app/views/admins/orders/show.html.erb
orderモデルにenumを追加しました。
数字で表示されていた箇所が文字になります。
> add.order.rb.enum

- app/controllers/orders_controller.rb
- app/controllers/products_controller.rb
- app/models/order.rb
- app/models/order_item.rb
- app/views/orders/confirm.html.erb
- app/views/orders/index.html.erb
- app/views/orders/new.html.erb
- app/views/orders/show.html.erb
order_itemを機能できるよう作成しました。
商品詳細ページ、詳細一覧を作成しました。
> Order item

- app/controllers/admins/customers_controller.rb
- app/views/admins/customers/edit.html.erb
- app/views/admins/customers/index.html.erb
- app/views/admins/customers/show.html.erb
- config/initializers/kaminari_config.rb
> admins_customer index,show,edit, kaminari

- app/controllers/cart_items_controller.rb
> add.cartitem.add_quantity

- app/views/customers/confirm.html.erb
- app/views/layouts/_header.html.erb
> headerとcustomerのcomfirm

- app/controllers/admins/categories_controller.rb
- app/controllers/admins/products_controller.rb
- app/controllers/shipping_addresses_controller.rb
上記にcreate,update時のif文追加とflash追加しました
> adminのcategory,productとshipping_address

- app/assets/stylesheets/application.scss
- app/views/admins/categories/show.html.erb
- app/views/admins/customers/index.html.erb
- app/views/admins/home/top.html.erb
- app/views/admins/orders/_ordercount.html.erb
- app/views/cart_items/index.html.erb
- app/views/customers/confirm.html.erb
- app/views/customers/edit.html.erb
- app/views/customers/show.html.erb
- app/views/home/top.html.erb
- app/views/layouts/_header.html.erb
- app/views/orders/index.html.erb
- app/views/products/_productlist.html.erb
- app/views/products/index.html.erb
- config/application.rb
- config/initializers/time_formats.rb
日付の表示、その他ビュー全体を修正しました。
商品一覧と管理者トップページの注文件数をパーシャル化して表示しています。
> [Update] date/views

- app/controllers/orders_controller.rb
コンフリクトで消えた箇所と追加
Fix
Cartitemの中身が注文確定されると
カート内を空にされます。
（一回注文が終わると空になる。）
> fix.cart_item

- app/controllers/admins/customers_controller.rb
- app/controllers/admins/orders_controller.rb
- app/controllers/cart_items_controller.rb
- app/controllers/customers_controller.rb
- app/controllers/orders_controller.rb
- app/controllers/products_controller.rb
- app/controllers/shipping_addresses_controller.rb
before aciton追加。shipping_addressのエラーメッセージ表示できる様コントローラー修正しました。
> controller系

- app/models/category.rb
- app/models/order.rb
- app/models/product.rb
- app/models/shipping_address.rb
モデル　バリデーションだけ
多分、コントローラかビューでエラがーでます。
> add.validates

- app/controllers/admins/orders_controller.rb
- app/controllers/admins/products_controller.rb
- app/controllers/shipping_addresses_controller.rb
> admin product,order shipping_address 訂正

- app/assets/javascripts/application.js
- app/controllers/admins/orders_controller.rb
- app/controllers/orders_controller.rb
- app/models/order.rb
- app/models/order_item.rb
- app/views/admins/orders/show.html.erb
make_statusを文字列で表示できるようにしました。
注文機能で引っかかる部分を修正しました。
> [Update] make_satus

- app/views/admins/customers/index.html.erb
- app/views/admins/orders/index.html.erb
- app/views/admins/products/index.html.erb
- app/views/cart_items/index.html.erb
- app/views/customers/show.html.erb
- app/views/orders/index.html.erb
- app/views/shipping_addresses/index.html.erb
> [Update] icon

- app/assets/javascripts/admins/order_items.coffee
- app/assets/stylesheets/admins/order_items.scss
- app/controllers/admins/order_items_controller.rb
- app/controllers/admins/orders_controller.rb
- app/controllers/cart_items_controller.rb
- app/controllers/orders_controller.rb
- app/helpers/admins/order_items_helper.rb
- app/models/order_item.rb
- app/views/admins/orders/show.html.erb
- app/views/orders/confirm.html.erb
- config/routes.rb
- test/controllers/admins/order_items_controller_test.rb
> fix.order_item_all

- app/views/admins/customers/edit.html.erb
- app/views/admins/customers/show.html.erb
- app/views/admins/orders/show.html.erb
- app/views/admins/products/edit.html.erb
- app/views/admins/products/new.html.erb
- app/views/admins/products/show.html.erb
- app/views/orders/confirm.html.erb
- app/views/orders/show.html.erb
> [Update] icon2

- app/controllers/application_controller.rb
- app/controllers/customers_controller.rb
上記テスト項目に合うように修正。
application_controller　ログアウト後の遷移先の設定。
customer_controller　　admin画面のaccount_statusに反映。
> application_controllerとcustomer_controller

- app/controllers/admins/products_controller.rb
- app/controllers/orders_controller.rb
- app/views/orders/confirm.html.erb
- config/routes.rb
> fix.product

- app/controllers/cart_items_controller.rb
- app/controllers/orders_controller.rb
- app/views/orders/show.html.erb
注文履歴詳細ページのステータス情報と日付情報を追記
カートから注文情報入力へいくときのbefore actionを追記しました。
> [Update] orde validation

- app/controllers/orders_controller.rb
> orders_controller

- app/controllers/orders_controller.rb
- app/views/orders/confirm.html.erb
配送先住所を注文の際に登録したら配送先住所一覧にのる、他はのらないようにした。
> [Update] shipping_address 3button

- app/controllers/admins/order_items_controller.rb
- app/controllers/admins/orders_controller.rb
- app/models/order.rb
make_statusとbuy_statusの連動を作成しました。
> [Update] make_status buy_status

- app/controllers/admins/categories_controller.rb
- app/controllers/home_controller.rb
- app/views/admins/categories/show.html.erb
- app/views/home/top.html.erb
- app/views/products/_productlist.html.erb
- app/views/products/index.html.erb
ページネーションがカテゴリー部分でエラーが出ていたので修正しました。
> [Fix] paginate errors
